<?= $rockfrontend->renderIf("sections/about.latte", "name=about") ?>
<?= $rockfrontend->renderIf("sections/music.latte", "name=music") ?>
<?= $rockfrontend->renderIf("sections/media.latte", "name=media") ?>
<?= $rockfrontend->renderIf("sections/events.latte", "name=events") ?>
<?= $rockfrontend->renderIf("sections/shop.latte", "name=shop") ?>
<?= $rockfrontend->renderIf("sections/shop-item.latte", "parent=shop") ?>
<?= $rockfrontend->renderIf("sections/promailer-subscribe.latte", "name=newsletter") ?>
<?= $rockfrontend->renderIf("sections/promailer-subscribe.latte", "name=subscribe") ?>
<?= $rockfrontend->renderIf("sections/contact.latte", "name=contact") ?>
<?= $rockfrontend->renderIf("sections/default-page.latte", "name=ai-policy|colophon|support|shop-policy|thank-you-for-your-purchase") ?>
<?= $rockfrontend->renderIf("sections/sitemap.latte", "name=sitemap") ?>